### PR TITLE
upgraded to mio v0.4

### PR DESCRIPTION
**Pull request by frederikbosch**
Just started with Rust and wanted to do something with RabbitMQ, came accross your library. Thanks for the work. Hope this pull request helps for the future.

Since I am really a Rust beginner, there might errors in the modifications I made.

### CODE REVIEW

**Comment by zslayton** [comment]
Thanks a lot for putting this together! I'm traveling for work at the moment, but I'll merge your PR in the next day or two.

**Comment by zslayton** [comment]
Would you mind tweaking the Cargo.toml file to specify version 0.4.x so other people don't get bit by my having used "*" everywhere? I'll open an issue to do the same for my other dependencies.

**Comment by frederikbosch** [comment]
Done.

**Comment by frederikbosch** [comment]
Since my PR for the updated README.MD, finally I managed to get the connection working. However, there seems to be a problem with this PR. It will only work with mio v3, and not with mio v4 together with this code. So, while Travis believes it is alright, there are still issues left.

**Comment by zslayton** [comment]
Thanks again!

**Comment by frederikbosch** [comment]
@zslayton There is a problem with the PR. Read my previous message: the example posted in the readme.md does not show similar behaviour as with mio v3. I guess there is more that should be changed in order to have mio v0.4 fully operatable.

**Comment by zslayton** [comment]
Ah, shoot. I missed that. I'll investigate. Are you seeing the error RE: `socket not connected`?

**Comment by frederikbosch** [comment]
Nope. There is a connection. But I dont see the messages printed with the v0.4 version. No idea why. But my debugging skills with rust are not up to standards yet.

**Comment by zslayton** [comment]
I'm going to revert this PR until we can figure it out. It looks like v0.4 of `mio` also included [its own version](http://rustdoc.s3-website-us-east-1.amazonaws.com/mio/master/mio/tcp/struct.TcpStream.html) of the `TcpStream` struct, so there's probably a lot of work for me to do to switch to that as well.

**Comment by frederikbosch** [comment]
Right, I already referenced that, and that made it compile. But that is not enough.

**Pull request merged**
